import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import fs from 'fs'
import path from 'path'

function writeEnvFileIfEnabled() {
  try {
    const shouldWrite = process.env.WRITE_ENV_FILE === '1' || process.env.WRITE_ENV_FILE === 'true'
    if (!shouldWrite) return
    const cwd = process.cwd()
    const envPath = path.join(cwd, '.env')
    const bakCandidates = ['env.bak', '.env.bak']
      .map((n) => path.join(cwd, n))
      .filter((p) => fs.existsSync(p))

    if (fs.existsSync(envPath)) {
      console.log('[writeenv] .env already exists, skip writing.')
      return
    }

    if (bakCandidates.length > 0) {
      fs.copyFileSync(bakCandidates[0], envPath)
      console.log(`[writeenv] Copied ${path.basename(bakCandidates[0])} -> .env`)
      return
    }

    // Fallback: synthesize .env from current process env (if provided)
    const lines = []
    const base = process.env.VITE_API_BASE || ''
    const debug = process.env.VITE_DEBUG || ''
    if (base) lines.push(`VITE_API_BASE=${base}`)
    if (debug) lines.push(`VITE_DEBUG=${debug}`)
    if (lines.length === 0) {
      lines.push('# Generated by writeenv; provide values via env or env.bak')
    }
    fs.writeFileSync(envPath, lines.join('\n') + '\n', 'utf8')
    console.log('[writeenv] Wrote .env with keys:', lines.map(l => l.split('=')[0]).join(', '))
  } catch (e) {
    console.warn('[writeenv] Failed to write .env:', e)
  }
}

// https://vitejs.dev/config/
export default defineConfig(({ command, mode }) => {
  // Write .env file on startup if explicitly enabled via env
  writeEnvFileIfEnabled()

  return {
    plugins: [react()],
    define: {},
    server: {
      port: 5173,
      strictPort: true,
      proxy: {
        // optional: you can uncomment to proxy API during dev
        // '/v1': 'http://localhost:8000',
        // '/auth': 'http://localhost:8000',
      },
    },
  }
})
