version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rabbit_api
    environment:
      - DATABASE_URL=sqlite:////data/dev.db
      - DEV_API_KEY=dev-secret
    volumes:
      - api_data:/data
    ports:
      - "8000:8000"

  web:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        VITE_API_BASE: http://localhost:8000
    container_name: rabbit_web
    depends_on:
      - api
    ports:
      - "5173:5173"

volumes:
  api_data:
